export const appActionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  INIT_CART: "INIT_CART",
  INCREMENT_CART: "INCREMENT_CART",
  DECREMENT_CART: "DECREMENT_CART"
}
